apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: backend
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
    spec:
      containers:
        - name: backend
          image: image: shashanka00315964/backend:latest


---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    app: backend
    tier: backend
    project: expense
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP


# sudo git clone https://github.com/ahmetb/kubectx /opt/kubectx
# sudo ln -s /opt/kubectx/kubectx /usr/local/bin/kubectx
# sudo ln -s /opt/kubectx/kubens /usr/local/bin/kubens